# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=100)),
                ('LastName', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Image', models.CharField(blank=True, max_length=60000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('FeedId', models.AutoField(primary_key=True, serialize=False)),
                ('FeedImage', models.CharField(max_length=60000)),
                ('Description', models.CharField(max_length=200)),
                ('FeedTime', models.CharField(max_length=200)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to='api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('LikeId', models.AutoField(primary_key=True, serialize=False)),
                ('LikeTime', models.CharField(max_length=200)),
                ('FeedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_on', to='api.Feeds')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_by', to='api.Account')),
            ],
        ),
    ]
